# Generated by Django 5.0.6 on 2024-06-06 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='categoria',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='fabricante',
            old_name='fabricante',
            new_name='nome',
        ),
    ]
