# Generated by Django 5.0.6 on 2024-05-27 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nome',
            new_name='nome_categoria',
        ),
        migrations.RenameField(
            model_name='fabricante',
            old_name='nome',
            new_name='nome_fabricante',
        ),
    ]
