# Generated by Django 5.0.6 on 2024-05-29 00:24

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='user',
            name='data_nascimento',
            field=models.DateField(blank=True, db_column='data_de_nascimento', help_text='Digite sua data de nascimento', null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_column='email', help_text='Digite o email do usuário', max_length=254, unique=True, verbose_name='Email do usuário'),
        ),
        migrations.AlterField(
            model_name='user',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('P', 'Prefiro não dizer')], db_column='genero', help_text='Gênero do usuário', max_length=1, null=True, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pais',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefone',
            field=models.CharField(blank=True, db_column='telefone', help_text='Digite seu número de celular ou telefone', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_column='nome_do_usuário', help_text='Digite o username', max_length=150, unique=True, verbose_name='Nome de usuário'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='Usuário',
        ),
    ]
