# Generated by Django 5.0.6 on 2024-06-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='user',
            name='estado',
        ),
    ]
